baseurl = "/"
languageCode = "en-US"
title = "Moses Alfaro"
# Enable comments by entering your Disqus shortname
disqusShortname = ""
# Enable Google Analytics by entering your tracking code
googleAnalytics = ""
theme = "hugo-sustain"

[permalinks]
  post = "/:year/:month/:day/:slug"

[params]
  avatar = "mosespic.jpg"
  author = "Moses Alfaro"
  description = "This website entails my resume, some projects from my computational biology class, and a little bit of personal information about me."

  # Custom assets can be linked with their paths relative to static/
  custom_css = []
  custom_js  = []

[params.social]
  Github        = "maa6493"
  Email         = "mosiealfaro3@utexas.edu"
  Twitter       = "mosesalfaro"

## Main Menu
[[menu.main]]
  name = "blog"
  weight = 100
  identifier = "blog"
  url = "/blog/"
[[menu.main]]
  name = "projects"
  identifier = "projects"
  weight = 200
  url = "/projects/"
[[menu.main]]
  name = "resume"
  identifier = "resume"
  weight = 300
  url = "/mosesresume.pdf"
